const TYPES = {
	GET_ALL_ARTICLES: 'GET_ALL_ARTICLES',
	SET_ALL_ARTICLES: 'SET_ALL_ARTICLES',
	SET_ARTICLES: 'SET_ARTICLES',
	SET_TAGS: 'SET_TAGS',
	SET_TERM_SEARCH: 'SET_TERM_SEARCH',
	SEARCH_ARTICLES: 'SEARCH_ARTICLES',
	SET_NO_DATA_FOUND: 'SET_NO_DATA_FOUND',
};

export default TYPES;
