const TYPES = {
	SET_LANGUAGE_CODE: 'SET_LANGUAGE_CODE',
	SET_LANGUAGE_MENU_ITEM_SELECTED: 'SET_LANGUAGE_MENU_ITEM_SELECTED',
	SET_LANGUAGE_LABEL: 'SET_LANGUAGE_LABEL',
	SET_DRAWER_OPEN: 'SET_DRAWER_OPEN',
	SET_IS_LOADING: 'SET_IS_LOADING',
};

export default TYPES;
